<a href="https://colab.research.google.com/github/minabusser4-maker/Python-ass/blob/main/Copy_of_Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Creating the fruits DataFrame
fruits = pd.DataFrame({'Apples': [30], 'Bananas': [21]})

# In Colab, just typing the variable name at the end displays it as a formatted table
fruits

   Apples  Bananas
0      30       21

In [ ]:
# Creating the fruit_sales DataFrame
fruit_sales = pd.DataFrame(
    [[35, 21], [41, 34]],
    columns=['Apples', 'Bananas'],
    index=['2017 Sales', '2018 Sales']
)

fruit_sales

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

In [ ]:
# Creating the ingredients Series
ingredients = pd.Series(
    ['4 cups', '1 cup', '2 large', '1 can'],
    index=['Flour', 'Milk', 'Eggs', 'Spam'],
    name='Dinner'
)

ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object